name: build the blog

on:
  push:
    branches:
      - compiled

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup hugo
        uses: peaceiris/actions-hugo@v3

      - name: build
        run: cd example && hugo --gc --minify --buildFuture --themesDir ../../
